# Generated by Django 5.2.9 on 2025-12-25 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_username',
            field=models.CharField(blank=True, help_text='Unique username (6+ chars). Letters, numbers, underscore only.', max_length=30, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.RegexValidator(message='Username must be letters, numbers or underscore', regex='^[A-Za-z0-9_]+$')]),
        ),
    ]
