# Generated by Django 5.2.9 on 2025-12-25 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('501', '501'), ('CRICKET', 'Cricket'), ('ATC', 'Around the Clock')], max_length=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('game_settings', models.JSONField(default=dict)),
                ('is_training', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('final_score', models.IntegerField(default=0)),
                ('final_position', models.IntegerField(blank=True, null=True)),
                ('statistics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['game', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_throws', models.IntegerField(default=0)),
                ('average_per_dart', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_per_round', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('checkout_attempts', models.IntegerField(default=0)),
                ('checkout_successes', models.IntegerField(default=0)),
                ('checkout_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('count_180s', models.IntegerField(default=0)),
                ('count_140_plus', models.IntegerField(default=0)),
                ('count_100_plus', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('marks_per_round', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('game_player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_stats', to='games.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='Throw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('throw_number', models.IntegerField()),
                ('score', models.IntegerField()),
                ('multiplier', models.IntegerField()),
                ('segment', models.IntegerField()),
                ('is_bust', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throws', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throws', to='games.gameplayer')),
            ],
            options={
                'ordering': ['game', 'round_number', 'player__order', 'throw_number'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['created_by', '-created_at'], name='games_game_created_e34885_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status'], name='games_game_status_da80c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game', 'order')},
        ),
        migrations.AddIndex(
            model_name='throw',
            index=models.Index(fields=['game', 'round_number'], name='games_throw_game_id_2e5c87_idx'),
        ),
        migrations.AddIndex(
            model_name='throw',
            index=models.Index(fields=['player'], name='games_throw_player__5d38c1_idx'),
        ),
    ]
