# Generated by Django 4.2.27 on 2025-12-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('501', '501'), ('301', '301'), ('401', '401'), ('701', '701'), ('1001', '1001'), ('CRICKET', 'Cricket'), ('CRICKET_CUTTHROAT', 'Cricket Cut-Throat'), ('ATC', 'Around the Clock'), ('SHANGHAI', 'Shanghai'), ('KILLER', 'Killer'), ('HALVE_IT', 'Halve-It'), ('BOBS_27', "Bob's 27"), ('SCRAM', 'Scram'), ('TIC_TAC_TOE', 'Tic-Tac-Toe'), ('ALL_FIVES', 'All-Fives'), ('MICKEY_MOUSE', 'Mickey Mouse'), ('ENGLISH_CRICKET', 'English Cricket'), ('GOTCHA', 'Gotcha')], max_length=20),
        ),
    ]
