# Generated by Django 4.2.27 on 2025-12-25 19:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_alter_game_game_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tournament_format', models.CharField(choices=[('SINGLE_ELIM', 'Single Elimination'), ('DOUBLE_ELIM', 'Double Elimination'), ('ROUND_ROBIN', 'Round Robin'), ('SWISS', 'Swiss System'), ('GROUPS_KO', 'Groups + Knockout'), ('LADDER', 'Ladder'), ('FFA', 'Free-for-All')], default='SINGLE_ELIM', max_length=20)),
                ('game_mode', models.CharField(choices=[('501', '501'), ('301', '301'), ('CRICKET', 'Cricket'), ('ATC', 'Around the Clock'), ('CUSTOM', 'Custom')], default='501', max_length=20)),
                ('game_settings', models.JSONField(default=dict)),
                ('max_participants', models.IntegerField(default=32, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(512)])),
                ('min_participants', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2)])),
                ('allow_public_registration', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('registration_password', models.CharField(blank=True, max_length=100)),
                ('min_skill_level', models.CharField(blank=True, choices=[('', 'No Restriction'), ('BEGINNER', 'Beginner+'), ('INTERMEDIATE', 'Intermediate+'), ('ADVANCED', 'Advanced+'), ('PROFESSIONAL', 'Professional Only')], max_length=20)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('estimated_duration_hours', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REG_OPEN', 'Registration Open'), ('REG_CLOSED', 'Registration Closed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('current_round', models.IntegerField(default=0)),
                ('prize_pool', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('prize_description', models.TextField(blank=True)),
                ('winner_xp_reward', models.IntegerField(default=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='tournament_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn'), ('DISQUALIFIED', 'Disqualified')], default='PENDING', max_length=20)),
                ('seed_number', models.IntegerField(blank=True, null=True)),
                ('final_placement', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['seed_number', '-points', '-wins', 'registered_at'],
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_losers_bracket', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['tournament', 'is_losers_bracket', 'round_number'],
                'unique_together': {('tournament', 'round_number', 'is_losers_bracket')},
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('WALKOVER', 'Walkover'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournaments.tournamentmatch')),
                ('player1_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player1', to='tournaments.tournamententry')),
                ('player2_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2', to='tournaments.tournamententry')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentround')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('winner_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournaments.tournamententry')),
            ],
            options={
                'ordering': ['round__round_number', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_invitations', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', '-start_time'], name='tournaments_status_f299b0_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['organizer', '-created_at'], name='tournaments_organiz_0d35f4_idx'),
        ),
    ]
