# Generated by Django 4.2.27 on 2025-12-25 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='allow_score_submission',
            field=models.BooleanField(default=True, help_text='Allow participants to submit match scores'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='score_passcode',
            field=models.CharField(blank=True, help_text='Passcode for participants to submit scores', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='rating_change',
            field=models.IntegerField(default=0, help_text='Rating change from this tournament'),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Total points scored across all matches'),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='tournament_points_earned',
            field=models.IntegerField(default=0, help_text='Points earned based on placement'),
        ),
        migrations.CreateModel(
            name='PlayerTournamentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1500, help_text='Current tournament rating')),
                ('peak_rating', models.IntegerField(default=1500)),
                ('lowest_rating', models.IntegerField(default=1500)),
                ('tournaments_played', models.IntegerField(default=0)),
                ('tournaments_won', models.IntegerField(default=0)),
                ('tournaments_runner_up', models.IntegerField(default=0)),
                ('tournaments_top_4', models.IntegerField(default=0)),
                ('total_matches_won', models.IntegerField(default=0)),
                ('total_matches_lost', models.IntegerField(default=0)),
                ('total_tournament_points', models.IntegerField(default=0)),
                ('skill_tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster')], default='BRONZE', max_length=20)),
                ('last_tournament_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='MatchScoreSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('passcode_used', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_submissions', to='tournaments.tournamentmatch')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_scores', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_scores', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_by_submission', to='tournaments.tournamententry')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='Current ranking in tournament')),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('matches_drawn', models.IntegerField(default=0)),
                ('points_for', models.IntegerField(default=0, help_text='Total points scored')),
                ('points_against', models.IntegerField(default=0, help_text='Total points conceded')),
                ('points_difference', models.IntegerField(default=0)),
                ('tournament_points', models.IntegerField(default=0, help_text='Points from wins/draws')),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('highest_score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournamententry')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['rank', '-tournament_points', '-points_difference'],
                'unique_together': {('tournament', 'entry')},
            },
        ),
    ]
