# Generated by Django 5.2.9 on 2025-12-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_allow_score_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private tournaments are hidden from public listing'),
        ),
    ]
