# Generated by Django 5.2.9 on 2025-12-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_is_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentstanding',
            options={'ordering': ['rank', '-tournament_points', '-points_difference', '-buchholz_score', '-sonneborn_berger', '-points_for']},
        ),
        migrations.AddField(
            model_name='tournamentstanding',
            name='buchholz_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Sum of opponents' scores (for Swiss)", max_digits=6),
        ),
        migrations.AddField(
            model_name='tournamentstanding',
            name='head_to_head_wins',
            field=models.IntegerField(default=0, help_text='Wins against tied opponents'),
        ),
        migrations.AddField(
            model_name='tournamentstanding',
            name='sonneborn_berger',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weighted opponent score', max_digits=6),
        ),
    ]
