# Generated by Django 5.2.9 on 2025-12-26 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_tournamentstanding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='live_scoring_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REG_OPEN', 'Registration Open'), ('REG_CLOSED', 'Registration Closed'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SCORE_UPDATE', 'Score Update'), ('LEG_START', 'Leg Start'), ('LEG_END', 'Leg End'), ('THROW', 'Throw'), ('CHECKOUT', 'Checkout'), ('PAUSE', 'Pause'), ('RESUME', 'Resume'), ('RESULT_OVERRIDE', 'Result Override'), ('ANNOUNCEMENT', 'Announcement')], max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.tournamentmatch')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
