# Generated by Django 5.2.9 on 2025-12-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('difficulty', models.CharField(default='Medium', max_length=40)),
                ('reward', models.CharField(default='+50 XP', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(default='General', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('level', models.CharField(default='Intermediate', max_length=40)),
                ('duration', models.CharField(default='30–45 min', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('drills', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='mode',
            field=models.CharField(choices=[('PROGRAM', 'Program'), ('DRILL', 'Drill'), ('CHALLENGE', 'Challenge'), ('BOBS_27', "Bob's 27"), ('CHECKOUT_PRACTICE', 'Checkout Practice'), ('FREE_PRACTICE', 'Free Practice'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
