# Generated by Django 4.2.27 on 2025-12-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingchallenge_trainingdrill_trainingprogram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='elapsed_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
    ]
