# Generated by Django 5.2.9 on 2025-12-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainingsession_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
