# Generated by Django 5.2.9 on 2025-12-25 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('win_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('best_game_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_180s', models.IntegerField(default=0)),
                ('total_140_plus', models.IntegerField(default=0)),
                ('total_100_plus', models.IntegerField(default=0)),
                ('stats_by_mode', models.JSONField(default=dict)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User statistics',
            },
        ),
        migrations.CreateModel(
            name='PersonalBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('achieved_in_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_bests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
                'indexes': [models.Index(fields=['user', 'game_mode'], name='user_stats__user_id_ec7b0a_idx')],
            },
        ),
    ]
