# Generated by Django 5.2.9 on 2025-12-25 21:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INSTALL', 'Install'), ('SESSION_START', 'Session Start'), ('SESSION_END', 'Session End'), ('SCREEN_VIEW', 'Screen View'), ('ACTION', 'Action')], max_length=30)),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('app_version', models.CharField(blank=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['event_type', '-occurred_at'], name='user_stats__event_t_719568_idx'), models.Index(fields=['platform', '-occurred_at'], name='user_stats__platfor_d57410_idx')],
            },
        ),
    ]
