# Generated by Django 5.2.9 on 2025-12-26 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.BooleanField(default=True, editable=False, unique=True)),
                ('tournaments_enabled', models.BooleanField(default=True, help_text='Enable tournament features')),
                ('training_enabled', models.BooleanField(default=True, help_text='Enable training features')),
                ('multiplayer_enabled', models.BooleanField(default=True, help_text='Enable multiplayer games')),
                ('friend_requests_enabled', models.BooleanField(default=True, help_text='Enable friend system')),
                ('leaderboards_enabled', models.BooleanField(default=True, help_text='Enable global leaderboards')),
                ('achievements_enabled', models.BooleanField(default=True, help_text='Enable achievements system')),
                ('max_active_games_per_user', models.IntegerField(default=10, help_text='Maximum concurrent active games')),
                ('max_tournaments_per_user', models.IntegerField(default=5, help_text='Maximum tournaments a user can organize')),
                ('max_tournament_participants', models.IntegerField(default=128, help_text='Global maximum tournament size')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, default='Oche180 is currently undergoing maintenance. Please check back soon!')),
                ('allow_new_registrations', models.BooleanField(default=True, help_text='Allow new user signups')),
                ('require_email_verification', models.BooleanField(default=False, help_text='Require email verification for new accounts')),
                ('profanity_filter_enabled', models.BooleanField(default=True, help_text='Enable profanity filtering in user-generated content')),
                ('auto_moderate_usernames', models.BooleanField(default=True, help_text='Automatically check usernames for inappropriate content')),
                ('chat_enabled', models.BooleanField(default=False, help_text='Enable in-app chat')),
                ('max_friends', models.IntegerField(default=100, help_text='Maximum friends per user')),
                ('xp_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Global XP multiplier (e.g., 1.5 for 50% bonus)', max_digits=3)),
                ('daily_login_xp', models.IntegerField(default=10, help_text='XP awarded for daily login')),
                ('max_games_per_day', models.IntegerField(default=100, help_text='Maximum games per user per day (0 = unlimited)')),
                ('max_api_calls_per_minute', models.IntegerField(default=60, help_text='API rate limit per user')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
